### ISSUE TITLE
error

### ISSUE THREAD

**Issue by centipedex** [94q/GhostSelfBot#1]
"Expecting property name enclosed in double quotes: line 3 column 20 (char 97)" what do i do?

**Comment by 5mf** [comment]
did you install __the__ requirements?

**Comment by centipedex** [comment]
yes, i installed all of them.

**Comment by 5mf** [comment]
reinstall python

**Comment by StvnedEagle1337** [comment]
lmfao bro

> reinstall python

**Comment by StvnedEagle1337** [comment]
Remove All comment in config.json.  Dev totally ignored the fact comments arent allowed in json

**Comment by 94q** [comment]
> Remove All comment in config.json. Dev totally ignored the fact comments arent allowed in json

Hello! Thanks for the fact that you helped to this issue. As you can see i’m not working on ghostselfbot anymore. Thank you for replying to this issue again. Have a great day! May i close this issue now?

**Comment by StvnedEagle1337** [comment]
> > Remove All comment in config.json. Dev totally ignored the fact comments arent allowed in json
> 
> Hello! Thanks for the fact that you helped to this issue. As you can see i’m not working on ghostselfbot anymore. Thank you for replying to this issue again. Have a great day! May i close this issue now?

Sure

**Comment by StvnedEagle1337** [comment]
> > Remove All comment in config.json. Dev totally ignored the fact comments arent allowed in json
> 
> Hello! Thanks for the fact that you helped to this issue. As you can see i’m not working on ghostselfbot anymore. Thank you for replying to this issue again. Have a great day! May i close this issue now?

I made a pull request for you, If it helps

**Comment by 94q** [comment]
> > > Remove All comment in config.json. Dev totally ignored the fact comments arent allowed in json
> > 
> > 
> > Hello! Thanks for the fact that you helped to this issue. As you can see i’m not working on ghostselfbot anymore. Thank you for replying to this issue again. Have a great day! May i close this issue now?
> 
> I made a pull request for you, If it helps

thank you, i will update the repository soon. I will give you credits for fixing config.json issue. I will close this issue now
